# Generated by Django 5.1 on 2026-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="contact_details",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="entity_name",
            field=models.CharField(default="", max_length=180),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="excavation_depth",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="excavation_timeline",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="kml_file",
            field=models.FileField(blank=True, null=True, upload_to="requests/kml/"),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="work_type",
            field=models.CharField(default="", max_length=180),
        ),
    ]
