# Generated by Django 5.1 on 2026-02-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_changerequest_contact_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changerequest",
            name="excavation_timeline",
        ),
        migrations.AddField(
            model_name="changerequest",
            name="excavation_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="excavation_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
